### ISSUE TITLE
Publish latest version to Jenkins update center

### ISSUE THREAD

**Issue by timja** [jenkinsci/environment-dashboard-plugin#173]
Hey @willwh

I think we were chatting about this on IRC.

Where did you get to with publishing the plugin?

Let me know if there's anything I can do to help

**Comment by willwh** [comment]
I didn't have any luck, I will try again this evening and post a full log in a gist, so we can take a look. Thanks much for the offer of help!

**Comment by willwh** [comment]
Not sure if you spot anything obvious here? Seems like my `~/.m2/settings.xml` is incorrect, as I am still getting a http 401 response.

https://gist.github.com/willwh/6c71b2b356a739bb8fac8426dad76d54

I have reset my password a couple of times, and subsequently updated the encrypted password from Artifactory in my `~/.m2.settings.xml` -> still the same result though.

**Comment by timja** [comment]
```

**Comment by willwh** [comment]
Yes, this evening I tried using the encrypted password, and the API key, both still result in a 401. I am not sure what else to try at this point, as following these, https://www.jenkins.io/doc/developer/publishing/releasing/

Would it be outrageous to add an additional maintainer to have someone else try and publish this?

**Comment by timja** [comment]
I’m happy to try publish it

**Comment by timja** [comment]
this should fix it https://github.com/jenkinsci/environment-dashboard-plugin/pull/174

**Comment by willwh** [comment]
Sorry for the lag @timja - merging this and publishing didn't solve it though. Hmph. I'll be around this week hopefully can finally get this figured out :+1:

**Comment by timja** [comment]
can you paste a redacted version of you settings.xml please?

**Comment by willwh** [comment]
```
<settings>
  <pluginGroups>
    <pluginGroup>org.jenkins-ci.tools</pluginGroup>
  </pluginGroups>
 
  <profiles>
    <!-- Give access to Jenkins plugins -->
    <profile>
      <id>jenkins</id>
      <activation>
        <activeByDefault>true</activeByDefault> <!-- change this to false, if you don't like to have it on per default -->
      </activation>
      <repositories>
        <repository>
          <id>repo.jenkins-ci.org</id>
          <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>repo.jenkins-ci.org</id>
          <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <mirrors>
    <mirror>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
      <mirrorOf>m.g.o-public,!jitpack.io</mirrorOf>
    </mirror>
  </mirrors>

  <servers>
    <server>
      <id>maven.jenkins-ci.org</id> <!-- For parent 1.397 or newer; this ID is used for historical reasons and independent of the actual host name -->
      <username>willwh</username>
      <password>REDACTED</password>
    </server>
  </servers>

</settings>

**Comment by timja** [comment]
I've created https://github.com/jenkinsci/environment-dashboard-plugin/pull/175 which will validate the publishing configuration for this plugin (+ fix the docs url)

**Comment by teewhey** [comment]
Any luck getting this update live?

**Comment by timja** [comment]
Well that worked, (https://github.com/jenkinsci/environment-dashboard-plugin/pull/175), would you like me to try publishing it @willwh?

**Comment by willwh** [comment]
@timja yes please, I reset everything again and re-tested, still a 401. I am ready to go rebuild my machine, it makes no sense!

**Comment by timja** [comment]
Worked for me:

> BUILD SUCCESS

That proves configuration, so something is wrong on your end =/
